version: "3"
services:
  nacos:
    hostname: nacos
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=nacos
      - NACOS_SERVER_IP=192.168.1.100
      - MYSQL_SERVICE_HOST=192.168.1.100
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
    volumes:
      - /home/nacos/logs:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always